epochs: 100
output_dir: tmp
checkpoints_dir: checkpoints
lambda_A: 10.0
lambda_B: 10.0
lambda_identity: 0.5
num_workers: 0

model:
  name: StarGAN2Model
  generator:
    name: Generator
    img_size: 256
    style_dim: 64
    max_conv_dim: 512
    w_hpf: 1
  discriminator:
    name: Discriminator
    img_size: 256
    num_domains: 64
    max_conv_dim: 3
    lambda_reg: 1
    lambda_cyc: 1
    lambda_ds: 1
    lambda_sty: 1
  style_encoder:
    name: StyleEncoder
    img_size: 256
    style_dim: 64
    num_domains: 2
    max_conv_dim: 512
  mapping_network:
    name: MappingNetwork
    latent_dim: 16
    style_dim: 64
    num_domains: 2
#  gan_mode: lsgan

dataset:
  train:
    name: StarGAN2Dataset
    trans_size: 256
    dataroot: /data/datasets/AFHQ/train
#    cls_list: [non-makeup, makeup]
    phase: train
    latent_dim: 16
    batch_size: 4
    transforms:
      - name: Resize
        size: [256, 256]
        interpolation: 'bicubic' #cv2.INTER_CUBIC
#      - name: RandomCrop
#        size: [256, 256]
      - name: RandomHorizontalFlip
        prob: 0.5
#      - name: ToTensor
#      - name: Normalize
#        mean: [0.5, 0.5, 0.5]
#        std: [0.5, 0.5, 0.5]

  test:
    name: StarGAN2Dataset
    trans_size: 256
    dataroot: /data/datasets/AFHQ/test
#    cls_list: [non-makeup, makeup]
    phase: test
    latent_dim: 16
    batch_size: 4
    transforms:
      - name: Resize
        size: [256, 256]
        interpolation: 'bicubic' #cv2.INTER_CUBIC
#      - name: RandomCrop
#        size: [256, 256]
      - name: RandomHorizontalFlip
        prob: 0.5
#      - name: ToTensor
#      - name: Normalize
#        mean: [0.5, 0.5, 0.5]
#        std: [0.5, 0.5, 0.5]

optimizer:
  name: Adam
  beta1: 0.5
  beta2: 0.5
  weight_decay: 1e-4

#lr_scheduler:
#  name: linear
#  learning_rate: 0.0002
#  start_epoch: 100
#  decay_epochs: 100
lr_f: 1e-6
lr: 1e-4



log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 1
